### ISSUE TITLE
Differences in CPU behavior cause failing x86 tests on Travis CI

### ISSUE THREAD

**Issue by mike-myers-tob** [trailofbits/remill#187]
Many of the Remill instruction tests fail on Travis, and not even deterministically. They do not fail locally on developer machines, so we have been ignoring the issue and letting it annoy us for a while now.

Sometimes all of the tests pass. Re-running the build job myself tonight I have seen 100% pass, one instruction test fail, or 3 fail, or so many fail that it stopped running tests.

### Usually failing
`FTST`

### Occasionally failing
 `TZCNT` and `LZCNT`

### Seen failing at least once
The floating-point conditional move instructions (all of these tests failed): `FCMOVNU`, `FCMOVNB`, `FCMOVNE`, `FCMOVBE`, `FCMOVNBE`, `FCMOVU`, etc.

## Tips for Troubleshooting on Travis CI
We have enabled "debug builds" on our Travis CI repo. By using the API, you can trigger a debug build session. Use your own authorization token in place of the `**********`. Use your own Job ID in place of the `314970938`.

```shell
curl -s -X POST \ 
  -H "Content-Type: application/json" \ 
  -H "Accept: application/json" \ 
  -H "Travis-API-Version: 3" \ 
  -H "Authorization: token *************" \
   -d "{\"quiet\": true}" \   https://api.travis-ci.org/job/314970938/debug
```

Then wait multiple minutes for a response from the API (sometimes it does not respond, just do it again). Check the status on https://travis-ci.org/trailofbits/remill/builds/ as well, it will eventually trigger and say "pending". Using the web UI, observe the build log for the line with SSH instructions.

SSH in, and run the following commands to perform the Travis build steps and debug the tests:
```shell
travis_run_before_install
travis_run_install
travis_run_before_script
travis_run_script
sudo apt-get install gdb
gdb ./tests/X86/run-amd64_avx-tests
```

As usual, you definitely want to comment out some of the tests rather than build them all.

Once in GDB, you can run steps similar to this:
```gdb
handle SIGFPE nostop noprint
set $native = (State *)&gNativeState
set $lifted = (State *)&gLiftedState
b /home/travis/build/trailofbits/remill/tests/X86/Run.cpp:564
run
p/x $native->rflag
p/x $lifted->rflag
```

To scroll up/down in the terminal session you have to use the awful `ctrl-b [` and then use the arrow keys until you want to stop with `q`. Suggest you just view the log in the Travis CI web UI.

***Note*** you will get booted after ~49 minutes.

**Comment by mike-myers-tob** [comment]
For `LZCNT`, the native state has `rflag.cf=0x0`, `zf=0x1`, whereas the lifted state has `rflag.cf=0x1`, `zf = 0x0`. The lifted state is what is expected according to the Intel manual.

However, `TZCNT` and `LZCNT` are documented to have alternate implementation behavior that would explain the differences we see. The Intel architecture manual states that "on processors that do not support LZCNT, the instruction byte encoding is executed as BSR." And likewise, processors without `TZCNT` will execute those opcodes as `BSF`.

The `cpuid` command ought to indicate if support for `TZCNT` or `LZCNT` were not present, but, even when these tests fail, the `cpuid` output indicates that these instructions are supported.

**Comment by mike-myers-tob** [comment]
For `FTST`, the difference in native and lifted state is the `RIP` register: it differs by two bytes (it is `0x49c4e6` in native, `0x49c4e4` in lifted).

Again, it seems like a different instruction was executed? Different instruction was compiled? Why would the instruction pointer be the only difference?

**Comment by mike-myers-tob** [comment]
We've managed to re-create the failing tests on another Ubuntu 14.04 Linux running on the KVM hypervisor on an Intel Xeon CPU, similar to Travis CI. We're seeing the `FCMOV` tests fail, and the `TZCNT` and the `LZCNT`.

Additional failing test cases:
* `FY2LXP1_1` with `ARG1=0x0`
* `FY2LX_1` with `ARG1=0x0`
* `FINCSTP_1` with `ARG1=0x0`
* `FDECSTP_1` with `ARG1=0x0`
* `FPATAN_1` with `ARG1=0x0`
* `FPTAN_1` with `ARG1=0x0`
* `FNOP_1` with `ARG1=0x0`
* `FXCHst0st2_1` with `ARG1=0x0`
* `FXCHst0st1_1` with `ARG1=0x0`
* `FXCHst0st0_1` with `ARG1=0x0`
* `FLD1_ST0_1` with `ARG1=0x0`
*  `FLD2T_ST0_1` with `ARG1=0x0`
* `FLD2E_ST0_1` with `ARG1=0x0`
* ` FLDPI_ST0_1` with `ARG1=0x0`
* `FLDLG2_ST0_1` with `ARG1=0x0`
* `FLDLN2_ST0_1` with `ARG1=0x0`
* `FLDZ_ST0_1` with `ARG1=0x0`

It's likely that this is a cascading error from one of the effects of `FLD`, which is a dependence for the other instructions to work right.

**Comment by mike-myers-tob** [comment]
On our Xeon/KVM test system, `LZCNT` (and therefore `TZCNT`) are not supported.

```shell
cpuid | grep LZCNT
      LZCNT advanced bit manipulation        = false
      LZCNT advanced bit manipulation        = false
      LZCNT advanced bit manipulation        = false
      LZCNT advanced bit manipulation        = false
```

So we need a CPU capabilities test to decide whether to include the `LZCNT` / `TZCNT` tests. It may not matter if Travis' system is still reporting them to be supported when it behaves like they are not.

As for the FPU instructions, the underlying issue is `state->x87.fxsave.ip`, and either Xeon-specific behavior or a bug with the field width, or both. Still debugging.

No new theories on `FTST` yet.

**Comment by mike-myers-tob** [comment]
I fixed the failing X87 test cases in commit.

Commit also fixes the `LZCNT` and `TZCNT` by adding "is this actually supported on this cpu?" checks and conditional jumps to the instruction tests. This also required back-porting the better lifting  from the AArch64 test runner as suggested by Peter, to support conditional branches in tests.

Alessandro's server with the Xeon and the KVM accurately reports not supporting these two instructions. So the checks now appropriately skip the tests and pass. Over on the Travis CI system though, based on its `cpuid` outputs on the command line, they may be reporting inaccurate support for instructions: I saw the tool list support, but then the instructions behaved like the CPU did not have support. So that sucks; the tests will probably fail on pathological systems like this. We can report the `cpuid` flag bug to the Travis team, or it might go away on its own when they upgrade, or it might have already gone away since they just upgraded their system images.

Next up, solving the `FTST` heisenbug with the `-0.0` case.

**Comment by mike-myers-tob** [comment]
All right, the X87 test cases were not fixed. In 32-bit test runs when `CS` is non-zero (a condition so far only encountered when running on one of these Xeon servers), then the FPU instruction tests where `x87.fxsave32.cs` is set to `state.seg.cs.flat` are effectively setting the former to `0`, whereas I think the intention was to set it to the `CS` that the native test would have had. https://github.com/trailofbits/remill/blob/8092ec0b2cc0312e6e9abe36c94dc1c669925aea/remill/Arch/X86/Semantics/X87.cpp#L58

This value of `0` is such because we don't preserve the state of the segment registers, only the general-purpose registers. https://github.com/trailofbits/remill/blob/8092ec0b2cc0312e6e9abe36c94dc1c669925aea/remill/Arch/X86/Semantics/X87.cpp#L58

We are a 64-bit test runner invoking 32-bit mode tests, but we can't `push CS` or `pop CS` from 64-bit mode assembly. Is there a trick by which we can maintain the segment registers for comparison, or should we zero out `lifted->x87.fxsave32.cs` to avoid comparison failures (on the x87 save-state structs) that will flunk the tests when native `CS` is non-zero?

**Comment by mike-myers-tob** [comment]
Fixed in https://github.com/trailofbits/remill/pull/192

**Comment by ranweiler** [comment]
@mike-myers-tob, I believe this issue remains unresolved, and was also masked by #205.
